"""Generates the FAKE RSA-2048 keypair committed in src/ga_mock/keypair.py.

Run ONCE, by hand, from the repo root:

    uv run --with cryptography python scripts/generate_keypair.py

The output is COMMITTED: the key only authenticates a mock, and publishing it
is the very mechanism that lets consumers (insights360 tests, dev .env) sign
valid assertions without a secrets infrastructure. Regenerating it invalidates
copies held by consumers — only do so knowingly.

`cryptography` is used ONLY HERE, for generation and PKCS#8 PEM
serialization, which must be flawless (real clients will load it). The mock's
runtime stays pure stdlib: it only reads the N/E/D integers.
"""

from __future__ import annotations

import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "src" / "ga_mock" / "keypair.py"

TEMPLATE = '''"""FAKE RSA-2048 keypair, committed in full knowledge of the fact.

It only authenticates a mock: publishing it is intentional — it's what lets
consumers (insights360 tests, dev .env) sign valid assertions without a
secrets infrastructure. Generated by scripts/generate_keypair.py —
regenerating it invalidates copies held by consumers.
"""

E = 65537

N = int(
{n_lines}
    16,
)

D = int(
{d_lines}
    16,
)

PRIVATE_KEY_ID = "{key_id}"

PEM_PRIVE = """{pem}"""
'''


def _hex_lines(value: int) -> str:
    hexa = f"{value:x}"
    chunks = [hexa[i : i + 84] for i in range(0, len(hexa), 84)]
    return "\n".join(f'    "{chunk}"' for chunk in chunks)


def main() -> None:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import padding, rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    numbers = key.private_numbers()
    pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    ).decode()

    # Self-check: the mock's stdlib arithmetic must produce the SAME
    # signature as cryptography (PKCS#1 v1.5 is deterministic), otherwise the
    # committed keypair would be inconsistent with rsa_min.
    sys.path.insert(0, str(ROOT / "src"))
    from ga_mock.rsa_min import sign, verify

    message = b"ga-mock check"
    expected = key.sign(message, padding.PKCS1v15(), hashes.SHA256())
    actual = sign(message, numbers.public_numbers.n, numbers.d)
    if expected != actual:
        raise SystemExit("sign() stdlib != cryptography — keypair NOT written")
    if not verify(message, actual, numbers.public_numbers.n, numbers.public_numbers.e):
        raise SystemExit("verify() stdlib failed — keypair NOT written")

    TARGET.write_text(
        TEMPLATE.format(
            n_lines=_hex_lines(numbers.public_numbers.n) + ",",
            d_lines=_hex_lines(numbers.d) + ",",
            key_id=secrets.token_hex(20),
            pem=pem,
        )
    )
    print(f"✓ {TARGET.relative_to(ROOT)} regenerated")


if __name__ == "__main__":
    main()
